### ISSUE TITLE
Error banner is not aligned

### ISSUE THREAD

**Issue by ttsvetko** [vmware/vmware-cloud-director-ui-components#178] opened 2020-08-19 11:29 UTC
Is there a reason to have left and right margin for the error banner - it looks misaligned:

`
clr-alert ::ng-deep .alert {
    margin-left: 24px;
    margin-right: 24px;
}
`

<img width="1536" alt="Screenshot 2020-08-19 at 14 26 56" src="https://user-images.githubusercontent.com/159775/90629622-5de3c980-e228-11ea-8874-72e5b3a4c05e.png">

**Comment by ryan-bradford** [comment] 2020-09-09 12:54
Marking this as a duplicate of https://github.com/vmware/vmware-cloud-director-ui-components/issues/172

**Closed by ryan-bradford** 2020-09-09 12:54 UTC
